const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('navi', {
  ask: (text) => ipcRenderer.send('navi:ask', text),
  onChunk: (cb) => ipcRenderer.on('navi:chunk', (_e, text) => cb(text)),
  onDone: (cb) => ipcRenderer.on('navi:done', () => cb()),
  onError: (cb) => ipcRenderer.on('navi:error', (_e, msg) => cb(msg)),
  consolidate: () => ipcRenderer.invoke('navi:consolidate'),
  syncMemory: () => ipcRenderer.invoke('navi:sync-memory'),
  profile: () => ipcRenderer.invoke('navi:profile'),
  getConfig: () => ipcRenderer.invoke('navi:get-config'),
  getTheme: () => ipcRenderer.invoke('navi:get-theme'),
  inspire: () => ipcRenderer.invoke('navi:inspire'),
  generateTheme: (description) => ipcRenderer.invoke('navi:generate-theme', description),
  setModel: (tier) => ipcRenderer.send('navi:set-model', tier),
  checkAuth: () => ipcRenderer.invoke('navi:check-auth'),
  applySetup: (setup) => ipcRenderer.invoke('navi:apply-setup', setup),
  voiceAvailable: () => ipcRenderer.invoke('navi:voice-available'),
  transcribe: (wav) => ipcRenderer.invoke('navi:transcribe', wav),
  voiceFallback: () => ipcRenderer.invoke('navi:voice-fallback'),
  voiceTtsAvailable: () => ipcRenderer.invoke('navi:voice-tts-available'),
  setVoice: (enabled) => ipcRenderer.send('navi:set-voice', enabled),
  onSpeakWav: (cb) => ipcRenderer.on('navi:speak-wav', (_e, wav) => cb(wav)),
  onVoiceAvailability: (cb) => ipcRenderer.on('navi:voice-availability', (_e, info) => cb(info)),
  onReminderStart: (cb) => ipcRenderer.on('navi:reminder-start', () => cb()),
  onMinutesStart: (cb) => ipcRenderer.on('navi:minutes-start', () => cb()),
  onUpdateAvailable: (cb) => ipcRenderer.on('navi:update-available', (_e, info) => cb(info)),
  openExternal: (url) => ipcRenderer.send('navi:open-external', url),
  onMemStatus: (cb) => ipcRenderer.on('navi:memstatus', (_e, status) => cb(status)),
  // 会議録音 (renderer/meeting.js ↔ main の録音ファイル追記・トレイ制御)
  meetingStart: (info) => ipcRenderer.send('navi:meeting-start', info),
  meetingChunk: (buf) => ipcRenderer.send('navi:meeting-chunk', buf),
  meetingStop: (info) => ipcRenderer.send('navi:meeting-stop', info),
  onMeetingControl: (cb) => ipcRenderer.on('navi:meeting-control', (_e, cmd) => cb(cmd)),
  onMeetingStatus: (cb) => ipcRenderer.on('navi:meeting-status', (_e, msg) => cb(msg)),
  close: () => ipcRenderer.send('navi:close'),
  minimize: () => ipcRenderer.send('navi:minimize'),
});
